version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    container_name: app
    command: sh -c "npm install && node index.js"
    volumes:
      - ./node:/usr/src/app
      # - /usr/src/app/node_modules # volume anonimo (link simbolico)
    tty: true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$MYSQL_ROOT_PASSWORD',
        ]
      interval: 5s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - app
